pipeline
{
    agent any
    stages
    {
        stage('Start')
        {
            steps
            {
                echo "Start Pipeline"
            }
        }
        stage('Availability Check')
        {
            steps
            {
                echo "Check if all required Tests, Modules, Reviews  and Designs of the feature are available "
            }
        }
        stage('Build')
        {
            steps
            {
                echo "Build Project"
            }
        }
        stage('Test & Analysis')
        {
            parallel
            {
                stage('Static Analysis')
                {
                    steps
                    {
                        echo "Static Analysis"
                    }
                }
                stage('Unit Test (off target)')
                {
                    steps
                    {
                        echo "Unit Test"
                    }
                }
                stage('Unit Test (on target)')
                {
                    steps
                    {
                        echo "Unit Test"
                    }
                }
            }
        }
        stage('Deploy')
        {
            steps
            {
                echo "Deploy" 
            }
        }
    }
    post
    {
        always {
            echo 'Clean Up the workspace'
            deleteDir()
        }
        success {
            echo 'The pipe succeded'
        }
        unstable {
            echo 'The pipe is unstable'
        }
        failure {
            echo 'the pipe failed'
        }
    }
}