@echo off
setlocal

set PRJ_LOC=%cd%
set TOOL_LOC=%PRJ_LOC%/tool
set ARM_TOOL_LOC=%TOOL_LOC%/arm-tool
set CYG_TOOL_LOC=%TOOL_LOC%/Cygwin
set CYGPAHT=%TOOL_LOC%/bin/cygpath.exe
set ARMCC5_ASMOPT=%ARM_TOOL_LOC%
set ARMCC5_CCOPT=%ARM_TOOL_LOC%
set ARMCC5_FROMELFOPT=%ARM_TOOL_LOC%
set ARMCC5_LINKOPT=%ARM_TOOL_LOC%

echo PRJ_LOC
echo %PRJ_LOC%
echo TOOL_LOC
echo %TOOL_LOC%
echo ARM_TOOL_LOC
echo %ARM_TOOL_LOC%
echo CYG_TOOL_LOC
echo %CYG_TOOL_LOC%
echo CYGPAHT
echo %CYGPAHT%
echo ARMCC5_ASMOPT
echo %ARMCC5_ASMOPT%
echo ARMCC5_CCOPT
echo %ARMCC5_CCOPT%
echo ARMCC5_FROMELFOPT
echo %ARMCC5_FROMELFOPT%
echo ARMCC5_LINKOPT
echo %ARMCC5_LINKOPT%

echo ARM Tool Chain: Compiling done

endlocal