node { 
    if (0)
    {
        stage ('example 1')
        {
            echo 'ex 1'
        }
        stage ('example 2')
        {
            echo 'ex 2'
        }
    }
    else 
    {
        stage ('example 1')
        {
            echo 'true ex 3'
        }
        stage ('example 2')
        {
            echo 'true ex 4'
        }
        parallel
        {
            stage ('test 1')
            {
                steps
                {
                    echo 'test 1'
                }
            }
            stage ('test 2')
            {
                steps{
                    for (int x = 0; x < 10 ;x++)
                    {}
                    echo 'test x '
                }
                
            }
        }
    }
}