node { 
    if (1)
    {
        stage ('example 1')
        {
            echo 'ex 1'
        }
        stage ('example 2')
        {
            echo 'ex 2'
        }
    }
    else 
    {
        stage ('example 1')
        {
            echo 'ex 1'
        }
        stage ('example 2')
        {
            echo 'ex 2'
        }
    }
}