node
{
    // Variables Declaration:
    File f_wdir;
    String s_wdir="pipe_wdir/"
    int success = 0;
    int suc_start = 0;
    int f_wdirExist = 0;

    stage('Start')
    {
        // Variables Declaration:
        File f_currDir;
        f_currDir = new File('.');
        f_wdir = new File(s_wdir);
        
        // Routine:
        println('ls'.execute().text);
        f_currDir.eachDirMatch(s_wdir,
        {
            string msg;
            println(msg+"Match: "+it);
            f_wdirExist = 1;
        });
        if(f_wdirExist == 0)
        {
            f_wdir.mkdir();
            f_wdirExist = 1;
        }
        println(['cd',$s_wdir].execute().text);
        println('ls'.execute().text);

    }
    suc_start = 1;
    stage('List')
    {
        echo 'List'
        //print(listModules("code/*/modules/src/"));
        print(listModules("*"));
    }
    stage('Build')
    {
        echo 'Build'
    }
    stage('Test')
    {
        parallel StaticCodeAnalysis:
        {
            echo 'Static Code Analysis'
        }, 
        UnitTest:
        {
            echo 'Unit Test'
        }
    }
    stage('Deploy')
    {
        echo 'Deploy'
    }
    stage('Stop')
    {
        println('ls'.execute().text);
        
        println('ls'.execute().text);
    }
    success = 1;
    if( success == 1)
    {
        echo "Successfull Pipeline run."
    }
    else
    {
        echo "Unsuccessfull Pipeline run."
    }
    if ( f_wdirExist == 1)
    {
        println(['cd','..'].execute().text);
        if(f_wdir != null)
        {
            f_wdir = new File(s_wdir);
        }
        f_wdir.deleteDir();
        f_wdirExist = 0;
    }
}





/**
* @description: This function is used to delete all files at a especial location
* @param:
*       -path: Add a String with the 
*/
int deleteDir(path)
{
    if (path?.trim())
    {
        respond = 'rm -fr $path'.execute();
        println(respond);
        return 0;
    }
    return 1;
}

/**
* @description: This function is used to delete all files at a especial location
* @param:
*       -path: Add a String with the 
*/
String listModules(path)
{
    //if (path?.trim())
    //{
        return 'ls $path | grep "*.h" | sed s/.h//h'.execute().text;
    //}
    //return ""
}

/**
* @description: This function is used to delete all files at a especial location
* @param:
*       -path: Add a String with the 
*/
void printSh(cmd)
{
   def sout = new StringBuilder();
   def proc = cmd.execute();
   println(proc.text);
}