node
{
    stage('Start')
    {
        echo 'Start'
    }
    stage('List')
    {
        echo 'List'
    }
    stage('Build')
    {
        echo 'Build'
    }
    stage('Test')
    {
        parallel StaticCodeAnalysis:
        {
            echo 'Static Code Analysis'
        }, UnitTest
        {
            echo 'Unit Test'
        }
    }
    stage('Deploy')
    {
        echo 'Deploy'
    }
    deleteDir("*");
}

/**
* @description: This function is used to delete all files at a especial location
* @param:
*       -path: Add a String with the 
*/
int deleteDir(path)
{
    if (path?.trim())
    {
        'rm -fr $path'.execute();
        return 0;
    }
    return 1;
}
