node
{
    def mods;
    def feats;
    stage('Start')
    {
        echo 'Start'

    }
    stage('List')
    {
        echo 'List'
        listModules("code/*/modules/src/");
    }
    stage('Build')
    {
        echo 'Build'
    }
    stage('Test')
    {
        parallel StaticCodeAnalysis:
        {
            echo 'Static Code Analysis'
        }, 
        UnitTest:
        {
            echo 'Unit Test'
        }
    }
    stage('Deploy')
    {
        echo 'Deploy'
        deleteDir("*");
        'ls'.execute();
    }
    
}

/**
* @description: This function is used to delete all files at a especial location
* @param:
*       -path: Add a String with the 
*/
int deleteDir(path)
{
    if (path?.trim())
    {
        respond = 'rm -fr $path'.execute();
        println(respond);
        return 0;
    }
    return 1;
}

/**
* @description: This function is used to delete all files at a especial location
* @param:
*       -path: Add a String with the 
*/
String[] listModules(path)
{
    def tmp;
    if (path?.trim())
    {
        tmp = 'ls -l $path | grep "*.h" | sed s/.h//h'.execute().text;
        println(tmp);
        return 0;
    }
    return 1;
}

